# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_add_photos_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('photo', 'user')]),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('timestamp',)},
        ),
    ]
