# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_rating_unique_user_and_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="photo",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="photo",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
