# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_add_deleted_field_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Section'),
        ),
    ]
