# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fotopruvodce.photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_remove_photo_and_thumbnail_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='Výška:')),
                ('width', models.PositiveIntegerField(verbose_name='Šířka:')),
                ('image', models.ImageField(height_field='height', upload_to=fotopruvodce.photos.models.upload_series_photo_fullpath, validators=[fotopruvodce.photos.models.validate_photo], verbose_name='Fotka:', width_field='width')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_photos', to='photos.Photo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
