# Generated by Django 5.1.1 on 2024-09-22 10:43

import django.db.models.deletion
import fotopruvodce.photos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_add_series_photo_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Zobrazit v galerii'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Smazáno'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, help_text='Pokud chcete text naformátovat, použijte značkovací jazyk <a href="https://cs.wikipedia.org/wiki/Markdown" target="_blank">Markdown &#128279;</a>.<br><br><b>### Nadpis</b>&crarr;<br><br>V rámci odstavce mohu zalamovat, ostavec bude &crarr;<br>ukončen až prázdným řádkem. Konec řádku &crarr;<br>uprostřed odstavce&blank;&blank;&blank;&crarr;<br>se udělá pomocí několika mezer na konci řádku.&crarr;<br>&crarr;<br>&nbsp;&nbsp;&nbsp;* položka seznamu <b>**tučně**</b>&crarr;<br>&nbsp;&nbsp;&nbsp;* položka seznamu <i>*kurzívou*</i>&crarr;<br>&nbsp;&nbsp;&nbsp;* položka seznamu <code>`neproporcionálně`</code>&crarr;<br>&crarr;<br><a href="">[odkaz](http://example.com)</a>&crarr;', verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to=fotopruvodce.photos.models.upload_photo_fullpath, validators=[fotopruvodce.photos.models.validate_photo], verbose_name='Fotka', width_field='photo_width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_height',
            field=models.PositiveIntegerField(verbose_name='Výška fotky'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_width',
            field=models.PositiveIntegerField(verbose_name='Šířka fotky'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.section', verbose_name='Sekce'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(height_field='thumbnail_height', upload_to=fotopruvodce.photos.models.upload_thumb_fullpath, validators=[fotopruvodce.photos.models.validate_thumbnail], verbose_name='Náhled', width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_height',
            field=models.PositiveIntegerField(verbose_name='Výška náhledu'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail_width',
            field=models.PositiveIntegerField(verbose_name='Šířka náhledu'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Vloženo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Název fotky'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='seriesphoto',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Výška'),
        ),
        migrations.AlterField(
            model_name='seriesphoto',
            name='image',
            field=models.ImageField(height_field='height', upload_to=fotopruvodce.photos.models.upload_series_photo_fullpath, validators=[fotopruvodce.photos.models.validate_photo], verbose_name='Fotka', width_field='width'),
        ),
        migrations.AlterField(
            model_name='seriesphoto',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Šířka'),
        ),
    ]
