# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models, transaction


@transaction.atomic
def fill_thread_and_level(apps, schema_editor):
    Comment = apps.get_model("discussion", "Comment")

    def get_tree(comment, _tree=None, _level=0):
        if _tree is None:
            _tree = []
        _tree.append((comment, _level))
        _level += 1
        for child in Comment.objects.filter(parent=comment):
            get_tree(child, _tree, _level)
        return _tree

    for main_comment in Comment.objects.filter(parent=None):
        for comment, level in get_tree(main_comment):
            comment.thread = main_comment.pk
            comment.level = level
            comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="thread",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(fill_thread_and_level),
    ]
