# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0003_alter_timestamp_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=25)),
                ("email", models.CharField(blank=True, max_length=64)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous",
                        to="discussion.Comment",
                    ),
                ),
            ],
        ),
    ]
