#!/bin/sh

set -e

case "$1" in
    configure)
        adduser --system --group --home /var/lib/fotopruvodce --shell /bin/false --no-create-home fotopruvodce

        chown -R fotopruvodce:fotopruvodce /var/lib/fotopruvodce/media/photos
        chown -R fotopruvodce:fotopruvodce /var/log/fotopruvodce
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
