# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayed_email',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='old_password',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
