# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models

from fotopruvodce.core.text import MARKDOWN_HELP_TEXT


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_add_old_fotopruvodce_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, help_text=MARKDOWN_HELP_TEXT),
        ),
    ]
