# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_markdown_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences_json',
            field=models.TextField(blank=True, verbose_name='Konfigurace'),
        ),
    ]
