# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_css",
            field=models.TextField(blank=True, verbose_name="CSS"),
        ),
    ]
