# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0009_add_series_photo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Zobrazit:')),
                ('timestamp', models.DateTimeField(verbose_name='Založeno:')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL, verbose_name='Lektor:')),
                ('photos', models.ManyToManyField(related_name='workshops', to='photos.Photo', verbose_name='Fotky:')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
